In [1]:
import numpy as np
import torch

## 1D array with numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) #element
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) #slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) #slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


## 2D array with numpy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

print(t.ndim)
print(t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
2
(4, 3)


## 1D array with PyTorch

In [6]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)


## 2D array with PyTorch

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                     ])

print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[:, :-1]) # 첫 번째 차원에서는 다 가져오되 두 번째 차원에서는 마지막꺼 제외하고 가져오기
print(t[:, :-1].size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
torch.Size([4, 2])


## broadcasting
두 텐서 크기가 다를 때 자동적으로 사이즈를 맞춰 주는 기능. 

In [ ]:
# same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3을 [[3, 3]]으로 변환해서 자동으로 계산
print(m1 + m2) # [[1, 2]] + [[3, 3]]

# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # => [2, 2]
m2 = torch.FloatTensor([[3], [4]]) # => [2, 2]
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication
matrix multiplication과 달리 multiplication은 행렬곱을 계산하지 않고
[2, 2] x [2, 1]을 [2, 2] x [2, 2]로 변환해 계산함 (두 번째 텐서 크기를 앞과 맞춤)

In [12]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

In [13]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [14]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0)) # 첫 번째 dim에 대한 평균 (2,) => [2., 3.] (세로 방향을 줄이기)
print(t.mean(dim=1)) # 두 번째 dim에 대한 평균 => [1.5, 3.5] (가로 방향을 줄이기)
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [17]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


## Max and Argmax

In [18]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.max())
print(t.max(dim=0))
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])
print(t.max(dim=1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## View (Reshape)

In [20]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
               
             [[6, 7, 8],
              [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape) # (2, 2, 3)

print(ft.view([-1, 3])) # 앞부분은 모르겠고 뒷부분의 차원을 3으로 (2x2, 3) = (4, 3)
print(ft.view([-1, 3]).shape)

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)


torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze
view 함수와 달리 dim의 element 갯수가 1인 경우에 reshape하는 함수 (없애줌)

In [27]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)
print(ft.squeeze(dim=0)) # 그대로
print(ft.squeeze(dim=1)) # 1짜리 차원 없어짐

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])
tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


## Unsqueeze
원하는 dim에 명시해서 1을 넣어줌 